import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { fileURLToPath } from "url";
import nodemailer from "nodemailer";
import { Resend } from "resend";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = Number(process.env.PORT) || 3000;

  app.use(express.json());

  const getTransporter = () => {
    const email = process.env.EMAIL || process.env.GMAIL_USER;
    const password = process.env.PASSWORD || process.env.GMAIL_APP_PASSWORD;
    const host = process.env.SMTP_SERVER || 'smtp.gmail.com';
    const port = parseInt(process.env.SMTP_PORT || '587');

    if (!email || !password) return null;

    return nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: {
        user: email,
        pass: password,
      },
    });
  };

  const sendEmail = async ({ to, subject, html, fromName }: { to: string, subject: string, html: string, fromName: string }) => {
    const resendApiKey = process.env.RESEND_API_KEY;
    
    // CRITICAL: Resend ONLY allows 'onboarding@resend.dev' or a verified domain.
    // If we use the user's Gmail/Email variable as 'from', Resend will reject it.
    let fromEmail = process.env.EMAIL || process.env.GMAIL_USER || "onboarding@resend.dev";

    if (resendApiKey) {
      console.log(`[SERVER] Dispatching via Resend to ${to}`);
      
      // If the fromEmail is NOT 'onboarding@resend.dev' and NOT a verified domain the user owns,
      // Resend will fail. For now, we force onboarding@resend.dev for safety if it looks like a generic email.
      if (!fromEmail.includes('@') || fromEmail.includes('gmail.com') || fromEmail.includes('yahoo.com')) {
        fromEmail = "onboarding@resend.dev";
      }

      const resend = new Resend(resendApiKey);
      const { data, error } = await resend.emails.send({
        from: `"${fromName}" <${fromEmail}>`,
        to: [to],
        subject: subject,
        html: html,
      });

      if (error) {
        console.error("[SERVER] Resend Error Detail:", JSON.stringify(error, null, 2));
        throw new Error(`Resend Error: ${error.message || 'Unknown Resend Error'}`);
      }
      return data;
    } else {
      console.log(`[SERVER] Dispatching via SMTP to ${to}`);
      const transporter = getTransporter();
      if (!transporter) throw new Error("No mail credentials found (Missing RESEND_API_KEY or SMTP variables)");

      try {
        return await transporter.sendMail({
          from: `"${fromName}" <${fromEmail}>`,
          to: to,
          subject: subject,
          html: html,
        });
      } catch (smtpError: any) {
        console.error("[SERVER] SMTP Error Detail:", smtpError);
        throw new Error(`SMTP Error: ${smtpError.message || 'Check your Gmail App Password'}`);
      }
    }
  };

  // API Routes
  app.post("/api/welcome-email", async (req, res) => {
    const { name, email } = req.body;
    console.log(`[SERVER] Dispatching welcome email to ${name} at ${email}`);
    
    try {
      await sendEmail({
        to: email,
        fromName: "WAVE SHIELD",
        subject: 'Welcome to WAVE SHIELD - Operating Guidelines',
        html: `
          <div style="font-family: 'Helvetica', 'Arial', sans-serif; max-width: 650px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 0px; background-color: #ffffff;">
            <div style="background-color: #0f172a; padding: 30px; text-align: center; color: white;">
              <h1 style="margin: 0; font-size: 24px; font-weight: 900; text-transform: uppercase; letter-spacing: 2px;">WAVE SHIELD</h1>
              <p style="margin: 10px 0 0 0; font-size: 12px; opacity: 0.7; letter-spacing: 1px;">AUTOGENERATED TECHNICAL DOCUMENT</p>
            </div>
            
            <div style="padding: 30px;">
              <p style="font-size: 16px; color: #1e293b; margin-top: 0;">Hello <strong>${name}</strong>,</p>
              <p style="font-size: 15px; color: #334155; line-height: 1.6; font-weight: 500;">Thanks for choosing WAVE SHIELD Analysis Tool for Reinforced Concrete.</p>
              
              <div style="background-color: #f8fafc; border-left: 4px solid #3b82f6; padding: 20px; margin: 25px 0;">
                <h3 style="margin-top: 0; font-size: 14px; text-transform: uppercase; color: #1e293b; letter-spacing: 1px;">Step-by-Step Usage Guide</h3>
                <ol style="font-size: 14px; color: #475569; padding-left: 20px; line-height: 1.8;">
                  <li><strong>Select Simulation Mode:</strong> Switch between "Single Point" for individual beams or "Batch Analysis" for comprehensive structural mapping.</li>
                  <li><strong>Configure Method:</strong> Choose <em>Raw (No Correction)</em> for direct paths, or <em>Perpendicular / Parallel</em> if rebar interference is present.</li>
                  <li><strong>Input Data:</strong> Enter the Path Length (mm) and the measured Pulse Time (µs) from your apparatus.</li>
                  <li><strong>Analyze:</strong> Review the real-time velocity (Vc) and the quality grading assigned based on IS 516.</li>
                  <li><strong>Export:</strong> Use the "Email Report" or "Download PDF" features to document your findings.</li>
                </ol>
              </div>

              <h3 style="font-size: 14px; color: #334155; text-transform: uppercase;">Available Correction Methods</h3>
              <ul style="font-size: 13px; color: #64748b; line-height: 1.6;">
                <li><strong>No Correction:</strong> Direct transmission through solid concrete sections.</li>
                <li><strong>Perpendicular Rebar:</strong> When the sonic path crosses a rebar at a 90-degree angle.</li>
                <li><strong>Parallel Rebar:</strong> When probes are placed near a rebar running parallel to the sonic path.</li>
              </ul>

              <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #f1f5f9;">
                <p style="font-size: 13px; color: #1e293b; margin-bottom: 5px;"><strong>Technical Support:</strong></p>
                <div style="font-size: 13px; color: #3b82f6; font-family: monospace;">
                  anandarao242004@gmail.com<br/>
                  kathir77@gmail.com<br/>
                  mdharshini5@gmail.com
                </div>
              </div>

              <div style="margin-top: 30px; background-color: #fee2e2; padding: 10px; border-radius: 2px; text-align: center;">
                <p style="font-size: 11px; color: #991b1b; margin: 0; font-weight: bold;">DO NOT REPLY: THIS IS A COMPUTER-GENERATED MESSAGE.</p>
              </div>
            </div>
            
            <div style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
              <p style="margin: 0; font-size: 11px; color: #94a3b8;">Thiagarajar College of Engineering - Department of Civil Engineering</p>
            </div>
          </div>
        `
      });
      res.json({ success: true, message: "Technical guidelines sent to your inbox." });
    } catch (error) {
      console.error("[SERVER] Error sending email:", error);
      res.status(500).json({ success: false, error: error instanceof Error ? error.message : "System failed to send email." });
    }
  });

  app.post("/api/send-report", async (req, res) => {
    const { name, email, results, method, parameters } = req.body;
    console.log(`[SERVER] Dispatching lab report to ${email}`);

    try {
      const isBatch = Array.isArray(results);
      
      let htmlContent = `
        <div style="font-family: sans-serif; max-width: 700px; margin: 0 auto; border: 2px solid #0f172a; padding: 30px;">
          <div style="background-color: #0f172a; padding: 20px; color: white; text-align: center;">
            <h1 style="margin: 0; font-size: 24px;">WAVE SHIELD ANALYSIS REPORT</h1>
            <p style="margin: 5px 0 0 0; font-size: 12px; opacity: 0.8;">Thiagarajar College of Engineering</p>
          </div>

          <div style="margin: 20px 0; border-bottom: 2px dashed #cbd5e1; padding-bottom: 15px;">
            <table style="width: 100%; font-size: 13px;">
              <tr>
                <td><strong>Tester:</strong> ${name}</td>
                <td style="text-align: right;"><strong>Date:</strong> ${new Date().toLocaleDateString()}</td>
              </tr>
              <tr>
                <td><strong>Email:</strong> ${email}</td>
                <td style="text-align: right;"><strong>Method:</strong> ${method}</td>
              </tr>
            </table>
          </div>
      `;

      if (!isBatch) {
        htmlContent += `
          <div style="background-color: #f8fafc; padding: 20px; border: 1px solid #e2e8f0;">
            <h3 style="margin-top: 0; color: #1e293b; font-size: 14px; text-transform: uppercase;">Single Point Analysis</h3>
            <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
              <tr><td style="padding: 4px 0;">Path Length (L):</td><td style="padding: 4px 0;">${parameters.pathLength} mm</td></tr>
              <tr><td style="padding: 4px 0;">Pulse Time (T):</td><td style="padding: 4px 0;">${parameters.pulseTime} µs</td></tr>
              <tr><td style="padding: 4px 0;">Measured Velocity (Vm):</td><td style="padding: 4px 0;">${results.measuredVelocity.toFixed(3)} km/s</td></tr>
              ${results.kFactor ? `<tr><td style="padding: 4px 0;">Correction Factor (k):</td><td style="padding: 4px 0;">${results.kFactor.toFixed(4)}</td></tr>` : ''}
              <tr style="color: #2563eb; font-weight: bold; font-size: 18px;">
                <td style="padding-top: 15px;">Corrected Velocity (Vc):</td>
                <td style="padding-top: 15px;">${results.correctedVelocity.toFixed(3)} km/s</td>
              </tr>
              <tr>
                <td style="padding-top: 5px;">Quality Grading:</td>
                <td style="padding-top: 5px;"><strong style="color: #059669;">${results.quality}</strong></td>
              </tr>
            </table>
          </div>
        `;
      } else {
        htmlContent += `
          <h3 style="color: #1e293b; font-size: 14px; text-transform: uppercase;">Batch Analysis Summary</h3>
          <table style="width: 100%; border-collapse: collapse; font-size: 10px;">
            <tr style="background-color: #0f172a; color: white;">
              <th style="padding: 6px; border: 1px solid #334155;">#</th>
              <th style="padding: 6px; border: 1px solid #334155;">Location</th>
              <th style="padding: 6px; border: 1px solid #334155;">L (mm)</th>
              <th style="padding: 6px; border: 1px solid #334155;">T (µs)</th>
              <th style="padding: 6px; border: 1px solid #334155;">Vm (km/s)</th>
              <th style="padding: 6px; border: 1px solid #334155;">k-Factor</th>
              <th style="padding: 6px; border: 1px solid #334155;">Vc (km/s)</th>
              <th style="padding: 6px; border: 1px solid #334155;">Grade</th>
            </tr>
            ${results.map((r: any, i: number) => `
              <tr>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center;">${i + 1}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0;">${r.location}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center;">${r.pathLength}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center;">${r.pulseTime}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center;">${r.results.measuredVelocity.toFixed(3)}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center;">${r.results.kFactor ? r.results.kFactor.toFixed(4) : '1.000'}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; text-align: center; font-weight: bold;">${r.results.correctedVelocity.toFixed(3)}</td>
                <td style="padding: 6px; border: 1px solid #e2e8f0; font-weight: bold;">${r.results.quality}</td>
              </tr>
            `).join('')}
          </table>
        `;
      }

      htmlContent += `
          <div style="margin-top: 40px; font-size: 10px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px;">
            This report was generated using the WAVE SHIELD Analysis Tool. Data is sensitive to rebar influence correction.
          </div>
        </div>
      `;

      await sendEmail({
        to: email,
        fromName: "WAVE SHIELD Report",
        subject: `[REPORT] WAVE SHIELD Analysis - ${new Date().toLocaleDateString()}`,
        html: htmlContent
      });

      res.json({ success: true, message: "Professional report dispatched to your email." });
    } catch (error) {
      console.error("[SERVER] Error sending report:", error);
      res.status(500).json({ success: false, error: error instanceof Error ? error.message : "System failed to dispatch email." });
    }
  });

  // Vite integration
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[UPV LAB SERVER] Running on http://localhost:${PORT}`);
  });
}

startServer();
